### ISSUE TITLE
Textures directory

### ISSUE THREAD

**Issue by ju5td0m7m1nd** [BonnierNews/react-native-3d-model-view#1]
Hi, it is really an awesome repository, great work!

Any suggestion on how can I import the whole directory of texture files?

thanks!

**Comment by johankasperi** [comment]
Hi! Thanks! I don't understand what you mean by "import the whole directory of texture files". Do your model has several texture files? Or do you want to include several textures to your react native project? Please provide an example of what you are trying to do.

**Comment by johankasperi** [comment]
Closing this now because an example has not been provided. Please reopen the issue again if the problem still exist.
