### ISSUE TITLE
Raycast support

### ISSUE THREAD

**Issue by agusvazquez** [BonnierNews/react-native-3d-model-view#10]
Hey Bonnier! Thanks for this awesome library!

I've got a requirement from my client to make the model touchable and select in some hex color the area where the model was touched. 

I was seeing within your code and you support the single tap inside a boolean but you never use it.

What I want to ask you is where would be the best place to code the Raycast logic and the callback for the javascript object and the selection animation so I can fork the repo and do it my self.

Thanks!

**Comment by harisanwar64** [comment]
Thanks @agusvazquez for your comment, want to ask same question regarding this library. Any kind of relevant would be highly appreciated.

**Comment by johankasperi** [comment]
Hi! Glad you like it 😄 

There is some raycasting already in the project in [`VirtualObjectARView`](https://github.com/BonnierNews/react-native-3d-model-view/blob/master/ios/ARKitInteraction/VirtualObjectARView.swift#L68) that handles the moving and rotating of the object. You could probably put your logic there for handling touches of selection of objects.

However I'm closing this issue for now but please make a PR if you have any success implementing what you are aiming for.
