### ISSUE TITLE
RCT3DModel-Swift.h file not found

### ISSUE THREAD

**Issue by hardikamal** [BonnierNews/react-native-3d-model-view#12]
Hi

RCT3DModel-Swift.h file is not found when compiling in Xcode.
My app language is Swift. I am using react native for 1 screen in my swift app. ARKit folder is also missing when installed via pod with pod 'RCT3DModel', :path => '../node_modules/react-native-3d-model-view' in POD file
How can i resolve this?

Thanks

**Comment by johankasperi** [comment]
Hmm I haven't got much experience from including React Native into Swift projects. Could you provide an example project with your setup so I can look into it?

**Comment by johankasperi** [comment]
Closing this now

**Comment by newah** [comment]
ended up linking manually, without pods.
important to add Header Search Paths `$(SRCROOT)/../../../ios/Pods/Headers/Public` to this subproject

**Comment by mydudechris** [comment]
I get the same issue when I manually link the RNFetchBlob to the project. I'm running the latest version of react native (installed today) on iOS 13.3. I linked manually because RNFetchBlob keeps evaluating to null and require doesn't work.

**Comment by marlon-wiprud** [comment]
> ended up linking manually, without pods.
> important to add Header Search Paths `$(SRCROOT)/../../../ios/Pods/Headers/Public` to this subproject

how were you able to link manually? I am not seeing the xcodeproj for this package in my node modules or its .a file

**Comment by BanshiARIT** [comment]
'RCT3DModel-Swift.h' file not found

**Comment by saeedtkh** [comment]
the same error I have! any update?

**Comment by rgazeredo** [comment]
I have the same issue

**Comment by SMKH-PRO** [comment]
Same issue

**Comment by syedibrahimt** [comment]
Any solution for this ?

**Comment by syedibrahimt** [comment]
> ended up linking manually, without pods. important to add Header Search Paths `$(SRCROOT)/../../../ios/Pods/Headers/Public` to this subproject

i linked manually but still getting same error

**Comment by lokendracodewave** [comment]
same issue - "RCT3DModel-Swift.h file not found"

**Comment by komelabbbas** [comment]
Any solution plz help

**Comment by DivyeshPonkiya** [comment]
> Hi
> 
> RCT3DModel-Swift.h file is not found when compiling in Xcode. My app language is Swift. I am using react native for 1 screen in my swift app. ARKit folder is also missing when installed via pod with pod 'RCT3DModel', :path => '../node_modules/react-native-3d-model-view' in POD file How can i resolve this?
> 
> Thanks

.../node_modules/react-native-3d-model-view/ios/
This path in

1.RCT3DARModelView.h
2.RCT3DARModelView.m
3.RCT3DARModelViewManager.h
4.RCT3DARModelViewManager.m

=>above 4 file delete from this path
=>make patch 
=>build clean from Xcode
=>clean after run first from Xcode
=>Xcode in build Setting -> swift compiler language -> swift language version select 4.2

try this step, i make sure this error remove and run
