### ISSUE TITLE
How to add swift

### ISSUE THREAD

**Issue by juliuscalvium** [BonnierNews/react-native-3d-model-view#14]
I can not get this running in react native. I have installed `react-native-3d-model-view` and the dependencies you mention. But it won't run when I try react-native run-ios
You mention :
> The ARModelView is written in Swift. So you need to add Swift to your project:

How do I do this?

**Comment by birger-fuehne** [comment]
In xcode, switch to the project navigator, and move to the App folder (where your AppDelegate.h and .m files are). Select "File"  -> "New " -> "File" and choose Swift file. Name it Empty.swift. This should bring up a popup asking whether to create a bridge header file. Confirm.

Now you can change the Swift version in you build settings if necessary.

**Comment by juliuscalvium** [comment]
Thank you for you reply. I have done what you've said and now I have the option to change the Swift Compiler language version... It's set to 3.2. What should I set it to?

**Comment by birger-fuehne** [comment]
4.2 seems to work.

**Comment by juliuscalvium** [comment]
Hi again. The only options for me are 3.2 or 4.0. I am on Xcode 9.2. When I try to set it to 4.0 and run `react-native run-ios` it fails. I cannot update Xcode at the point for other reasons. Any suggestions?

<img width="957" alt="screen shot 2018-11-09 at 10 17 22" src="https://user-images.githubusercontent.com/43952200/48256868-cd4c4880-e408-11e8-8a00-c07e98eba4d1.png">

**Comment by dlindstrm** [comment]
@juliuscalvium try upgrading Xcode to 10 and use Swift 4.2.

**Comment by johankasperi** [comment]
If you want to use older version of Swift than 4.2 you can use [release 1.1.17](https://github.com/BonnierNews/react-native-3d-model-view/tree/release/1.1.17)
