### ISSUE TITLE
Remove black background from 3d object

### ISSUE THREAD

**Issue by Shoilev** [BonnierNews/react-native-3d-model-view#16]
Hello,

I am using ModelScreen.js [example ](https://github.com/BonnierNews/react-native-3d-model-view/blob/master/example/components/ModelScreen.js)in my app. And everything is running perfectly. 
But there is an issue with the background of the 3d object. When I set backgroundColor to 'transparent'
or remove at all the backgroundColor property. The black box still appears. Is there a way to remove this black background and to make it transparent? 

I have attached an image how it looks on my android emulator under windows machine.
![capture](https://user-images.githubusercontent.com/5407591/52355439-01043200-2a3b-11e9-9029-c6d6acbccd49.JPG)

**Comment by johankasperi** [comment]
`backgroundColor: transparent` is unfortunately not possible on android. This is due to the OpenGL scene that has black as default background.
