### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RCT3DARModelView" was not found in the UIManager.

### ISSUE THREAD

**Issue by vikramhegde58** [BonnierNews/react-native-3d-model-view#18]
hi i am facing this issue in android.

**Comment by johankasperi** [comment]
Seems like you haven't properly linked the library? https://facebook.github.io/react-native/docs/linking-libraries-ios

**Comment by vikramhegde58** [comment]
so you are saying it will work in android also right??

**Comment by johankasperi** [comment]
Yes it will run on android

**Comment by vikramhegde58** [comment]
Thanks for the help will check what's wrong with the linking.

**Comment by Muhamman78** [comment]
i am facing the same issue.. i have even linked it right. Please tell me how to fix it ?
