### ISSUE TITLE
library not found for -lswiftModelIO for architecture x86_64

### ISSUE THREAD

**Issue by RadiksMan** [BonnierNews/react-native-3d-model-view#3]
On fresh react-native app, after `yarn add react-native-3d-model-view` (and `react-native-zip-archive`, `react-native-fetch-blob` and `react-native-fs` )  and `react-native link`, when I try to react-native run-ios, build fails with following:
![1ce27cfe3d](https://user-images.githubusercontent.com/11598684/37955223-aef5bae8-31b0-11e8-8ccd-e120c8d41998.jpg)

When i run project from example folder(this repo) in ios simulator - everything is fine (3d model shows)

**Comment by johankasperi** [comment]
You need to add Swift to your iOS project since the AR functionality is written in Swift. The easiest way to do so is to add a `Empty.swift` file in the iOS project (see: https://github.com/BonnierNews/react-native-3d-model-view/blob/master/example/ios/example/Empty.swift). Sorry for not declaring this in the installation docs. Will add it asap

**Comment by RadiksMan** [comment]
@johankasperi

**Comment by RadiksMan** [comment]
@johankasperi  thanks for the comment but adding `Empty.swift` did not help - there was the same error
My order of actions:
`react-native init AwesomeProject`
`yarn add react-native-3d-model-view react-native-zip-archive react-native-fetch-blob react-native-fs`
add `Empty.swift` file
`react-native link`
get Error:
`ld: library not found for -lswiftModelIO for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by RadiksMan** [comment]
I managed,  more detail how to add swift in project - [stackoverflow](https://stackoverflow.com/questions/46338588/xcode-9-swift-language-version-swift-version/46339401)
Thanks!

**Comment by hardikamal** [comment]
@johankasperi What if the main project is written in swift?

**Comment by keyOfVv** [comment]
Keep at least one `.swift` file in project and set `Building settings` -> `Always Embed Swift Standard Libraries` as `YES`.
