### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by mydudechris** [BonnierNews/react-native-3d-model-view#6]
Trying to run the example project on my machine with the iOS simulator and get the following:

** BUILD FAILED **

The following build commands failed:

CompileSwift normal x86_64 /Users/Chris/Dev/react-native-3d-model-view/example/node_modules/react-native-3d-model-view/ios/ARKitInteraction/ARView+ARSCNViewDelegate.swift

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

Installing build/Build/Products/Debug-iphonesimulator/example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by johankasperi** [comment]
Hi! This should be solved in version 1.1.16. Please open a new issue otherwise.
