### ISSUE TITLE
Can't compile on iOS

### ISSUE THREAD

**Issue by agusvazquez** [BonnierNews/react-native-3d-model-view#8]
Hello Bonnier

When I'm trying to compile this lib into iOS it throws this exception.

/node_modules/react-native-3d-model-view/ios/ARKitInteraction/ARView+ARSCNViewDelegate.swift:133:9: switch must be exhaustive

        switch self {

More info here.
https://stackoverflow.com/questions/26686542/exhaustive-condition-of-switch-case-in-swift

Cheers

**Comment by agusvazquez** [comment]
To fix it i think you should add on the archive.

/ARKitInteraction/ARView+ARSCNViewDelegate.swift

on line 133, that switch case, add a default value like this.

`
default:
            return 0 //Or throw an exception
        }
`

**Comment by johankasperi** [comment]
Hi! Thanks for the info. I've added that line in version 1.1.16. Please open a new issue if the problem still exist.
